force-app/main/default/objects/Order/fields/Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Balance_Due__c</fullName>
    <formula>TotalAmount -  Total_Amount_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <formula>Quote.Discount</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Good_Available__c.field-meta.xml
<CustomField>
    <fullName>Good_Available__c</fullName>
    <label>Good Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ex Stock Dubai</fullName>
            </value>
            <value>
                <fullName>5 - 7 Days from LPO and Cleared Funds</fullName>
            </value>
            <value>
                <fullName>7-10 days from LPO and Cleared Funds</fullName>
            </value>
            <value>
                <fullName>15 Days from LPO and Cleared Funds</fullName>
            </value>
            <value>
                <fullName>4-6 Weeks from LPO and cleared funds</fullName>
            </value>
            <value>
                <fullName>5-6 Weeks from LPO and cleared funds</fullName>
            </value>
            <value>
                <fullName>10-12 Weeks from LPO and cleared funds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EX Works</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Air Freight</fullName>
            </value>
            <value>
                <fullName>Sea Freight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Supply_Type__c.field-meta.xml
<CustomField>
    <fullName>Supply_Type__c</fullName>
    <label>Supply Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supply &amp; Installation</fullName>
            </value>
            <value>
                <fullName>Supply Only</fullName>
            </value>
            <value>
                <fullName>Supply With Delivery</fullName>
            </value>
            <value>
                <fullName>Installation Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Net_Area_Sqm_Lm__c.field-meta.xml
<CustomField>
    <fullName>Net_Area_Sqm_Lm__c</fullName>
    <label>Net Area (Sqm/Lm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Quantity_SQM__c.field-meta.xml
<CustomField>
    <fullName>Quantity_SQM__c</fullName>
    <label>Quantity (SQM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount__c</fullName>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Overall Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Discounted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Amount__c</fullName>
    <label>Discounted Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Good_Available__c.field-meta.xml
<CustomField>
    <fullName>Good_Available__c</fullName>
    <label>Good Available</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ex Stock Dubai</fullName>
            </value>
            <value>
                <fullName>5 - 7 Days from LPO and Cleared Funds</fullName>
            </value>
            <value>
                <fullName>7-10 days from LPO and Cleared Funds</fullName>
            </value>
            <value>
                <fullName>15 Days from LPO and Cleared Funds</fullName>
            </value>
            <value>
                <fullName>4-6 Weeks from LPO and cleared funds</fullName>
            </value>
            <value>
                <fullName>5-6 Weeks from LPO and cleared funds</fullName>
            </value>
            <value>
                <fullName>10-12 Weeks from LPO and cleared funds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Warehouse - DIP 2 (597-733)</fullName>
            </value>
            <value>
                <fullName>Warehouse - Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>QuoteLineItem.Gross_Amount__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/SalesOrderPdfController.cls
public with sharing class SalesOrderPdfController {
    public Order order { get; set; }
    public List<OrderItem> orderProducts { get; set; }
    
    public SalesOrderPdfController() {
        String orderId = ApexPages.currentPage().getParameters().get('id');
        
        if (String.isNotBlank(orderId)) {
            loadOrderData(orderId);
        }
    }
    
    public SalesOrderPdfController(ApexPages.StandardController stdController) {
        String orderId = stdController.getId();
        if (String.isNotBlank(orderId)) {
            loadOrderData(orderId);
        }
    }
    //Goods_Available__c, Payment_Terms__c, Other_Instructions__c, Terms_and_Conditions__c, Account.TRN__c
    private void loadOrderData(String orderId) {
        try {
            order = [SELECT Id, Name, OrderNumber, CreatedDate, Opportunity.Name, Sales_Rep__r.Name, Discounted_Amount__c,
                     Total_Price__c, VAT__c, Tax_Amount__c, Grand_Total__c, Account.Phone, Branch__r.Name, Payment_Terms__c,
                     Account.ShippingAddress, Account.ShippingStreet, Account.ShippingCity, Discount__c, Good_Available__c, CurrencyIsoCode,
                     Supply_Type__c, Shipping_Method__c, Account.ShippingState, Quote.Email, Branch__r.Branch_Phone__c, Balance_Due__c,
                     Owner.Name, Account.BillingStreet, Account.BillingCity, Account.ShippingCountry, Account.ShippingPostalCode,
                     Account.Name, Account.AccountNumber, Account.BillingState, Account.BillingPostalCode, Account.BillingCountry,
                     Contact__r.Name, Contact__r.Phone, Contact__r.MobilePhone, Contact__r.Email, Branch__r.Branch_Address__c
                     FROM Order 
                     WHERE Id = :orderId 
                     LIMIT 1];
            
            orderProducts = [SELECT Id, Product2.Name, Product2.ProductCode, Gross_Amount__c, CurrencyIsoCode,
                              Description, Quantity, UnitPrice, TotalPrice, Discounted_Price__c, Quantity_SQM__c,
                              Location__c, Product2.Box_s_Per_Pallet__c, Product2.Weight_Per_Box_PCS_Kg__c,
                              Net_Area_Sqm_Lm__c, Unit__c, Discount__c, Product2.Primary_Consumption_Unit__c
                              FROM OrderItem 
                              WHERE OrderId = :order.Id
                             AND (NOT (Product2.Name LIKE '%Discount%'
                                   OR Product2.Name LIKE '%discount%'
                                   OR Description LIKE '%discount%'
                                   OR Description LIKE '%Discount%'))
                              Order By OrderItemNumber ASC];
            
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                                                       'Error loading quote data: ' + e.getMessage()));
        }
    }
    
    public Decimal getVATPercentage() {
        return 5.0;
    }

}